Loaded module: python3/3.7.5
Loaded dependency [cudnn/v7.6.5.32-prod-cuda-10.0]: cuda/10.0
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.0
Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 348, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 299, in main_worker
    train(train_loader, model, scheduler, optimizer, epoch, args)
  File "train.py", line 137, in train
    for idx, (images, annotations) in enumerate(train_loader):
ValueError: too many values to unpack (expected 2)
Loaded module: python3/3.7.5
Loaded dependency [cudnn/v7.6.5.32-prod-cuda-10.0]: cuda/10.0
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.0
Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 348, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 299, in main_worker
    train(train_loader, model, scheduler, optimizer, epoch, args)
  File "train.py", line 140, in train
    classification_loss, regression_loss = model([images, annotations])
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/fets/git/EfficientDet.Pytorch/models/efficientdet.py", line 62, in forward
    x = self.extract_feat(inputs)
  File "/work3/fets/git/EfficientDet.Pytorch/models/efficientdet.py", line 99, in extract_feat
    x = self.neck(x[-5:])
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/fets/git/EfficientDet.Pytorch/models/bifpn.py", line 108, in forward
    laterals = bifpn_module(laterals)
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/fets/git/EfficientDet.Pytorch/models/bifpn.py", line 190, in forward
    pathtd[i], scale_factor=2, mode='nearest'))/(w1[0, i-1] + w1[1, i-1] + self.eps)
RuntimeError: The size of tensor a (13) must match the size of tensor b (12) at non-singleton dimension 3
Loaded module: python3/3.7.5
Loaded dependency [cudnn/v7.6.5.32-prod-cuda-10.0]: cuda/10.0
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.0
None
None
None
Traceback (most recent call last):
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/appl/python/3.7.5/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/appl/python/3.7.5/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 27342) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 348, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 299, in main_worker
    train(train_loader, model, scheduler, optimizer, epoch, args)
  File "train.py", line 137, in train
    for idx, sample in enumerate(train_loader):
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _get_data
    success, data = self._try_get_data()
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 27342, 27344, 27346) exited unexpectedly
Loaded module: python3/3.7.5
Loaded dependency [cudnn/v7.6.5.32-prod-cuda-10.0]: cuda/10.0
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.0
Loaded module: python3/3.7.5
Loaded dependency [cudnn/v7.6.5.32-prod-cuda-10.0]: cuda/10.0
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.0
Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 348, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 299, in main_worker
    train(train_loader, model, scheduler, optimizer, epoch, args)
  File "train.py", line 138, in train
    images = sample['img'].cuda().float()
TypeError: list indices must be integers or slices, not str
Loaded module: python3/3.7.5
Loaded dependency [cudnn/v7.6.5.32-prod-cuda-10.0]: cuda/10.0
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.0
Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 348, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 299, in main_worker
    train(train_loader, model, scheduler, optimizer, epoch, args)
  File "train.py", line 137, in train
    for idx, sample in enumerate(train_loader):
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
  File "/work3/fets/git/EfficientDet.Pytorch/datasets/csv.py", line 102, in __getitem__
    return self._fieldnames
  File "/work3/fets/git/EfficientDet.Pytorch/datasets/csv.py", line 112, in load_image
    row = next(self.reader)
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/skimage/io/_io.py", line 48, in imread
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/imageio/core/functions.py", line 264, in imread
  File "/work3/fets/git/EfficientDet.Pytorch/venv/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
ValueError: Could not find a format to read the specified file in mode 'i'
Loaded module: python3/3.7.5
Loaded dependency [cudnn/v7.6.5.32-prod-cuda-10.0]: cuda/10.0
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.0
